[2025-01-01 04:11:38 +0000] [4714] [INFO] Shutting down: Master
 [2025-01-01 04:11:38 +0000] [5382] [INFO] Starting gunicorn 21.2.0
[2025-01-01 04:11:38 +0000] [5382] [INFO] Listening at: http://0.0.0.0:5000 (5382)
[2025-01-01 04:11:38 +0000] [5382] [INFO] Using worker: sync
[2025-01-01 04:11:38 +0000] [5387] [INFO] Booting worker with pid: 5387
              precision    recall  f1-score   support

           0       1.00      0.83      0.91         6
           1       0.86      1.00      0.92         6

    accuracy                           0.92        12
   macro avg       0.93      0.92      0.92        12
weighted avg       0.93      0.92      0.92        12

[2025-01-01 04:11:46,922] ERROR in app: Exception on /team/gunn [GET]
Traceback (most recent call last):
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/main.py", line 1420, in team_page
    return render_template('teams.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/runner/Final-Project-112424/templates/teams.html", line 224, in top-level template code
    <td><a href="{{ url_for('player_stats', player_name=player.name, team_color='black' if game.home_away == 'Home' else 'white') }}">{{ player.name }}</a></td>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Final-Project-112424/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'game' is undefined